name: Build Kodi Addon ZIP and MD5

on:
  push:
    branches: [ main ]
    paths:
      - 'skin.CarPc-Carbon/**'
      - 'addons.xml'
      - '.github/workflows/build_kodi_addon.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Atualizar submodules para o remoto (main)
        run: |
          git submodule update --init --recursive --remote

      - name: Set up variables
        id: vars
        run: |
          ADDON_ID="skin.CarPc-Carbon"
          VERSION=$(grep -Po '^<addon[^>]*version="\K[^"]+' skin.CarPc-Carbon/addon.xml | head -n1 | tr -d '\r\n')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV

      - name: Create addon ZIP (100% compatível)
        run: |
          cd $GITHUB_WORKSPACE
          zip -r zips/$ADDON_ID/$ADDON_ID-$VERSION.zip $ADDON_ID
        shell: bash
    
      - name: Atualiza versão do skin no addons.xml raiz
        run: |
            VERSION=$(grep -Po '^<addon[^>]*version="\K[^"]+' skin.CarPc-Carbon/addon.xml | head -n1 | tr -d '\r\n')
            sed -i "s/\(<addon id=\"skin.CarPc-Carbon\" [^>]*version=\"\)[^\"]*\(\"\)/\1$VERSION\2/" addons.xml
            grep 'skin.CarPc-Carbon' addons.xml

      - name: Generate MD5 for addons.xml
        run: |
          md5sum addons.xml | awk '{print $1}' > addons.xml.md5

      - run: |
          cat addons.xml
          git status
          git diff

      - name: Commit and push build artifacts
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Build addon ZIP and update MD5 [bot]'
          branch: main
