name: Criar Release e AtualizaÃ§Ã£o

on:
  push:
    tags:
      - 'v*'  # Gera um release quando um tag comeÃ§ando com "v" for feita

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Clonar repositÃ³rio
        uses: actions/checkout@v4

      - name: ğŸ“¦ Criar update.zip
        run: |
          zip -r update.zip scripts/

      - name: ğŸš€ Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          name: 'Release ${{github.ref_name}}'
          tag_name: ${{ github.ref_name }}
          body: 'Esta versÃ£o contÃ©m a atualizaÃ§Ã£o do script.'
          files: update.zip
          draft: false
          prerelease: false